name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  REGISTRY: bzzeatscontainers.azurecr.io
  FRONTEND_IMAGE: eatsfrontend
  BACKEND_IMAGE: eatsbackend
  RESOURCE_GROUP: dauti
  WEBAPP_NAME_FRONTEND: bzzeats-frontend
  WEBAPP_NAME_BACKEND: bzzeats-backend
  AZURE_SP_USERNAME: ${{ secrets.AZURE_SP_USERNAME }}
  AZURE_SP_PASSWORD: ${{ secrets.AZURE_SP_PASSWORD }}
  AZURE_SP_TENANT: ${{ secrets.AZURE_SP_TENANT }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login for frontend image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push frontend Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build --no-cache -f src/frontend/Dockerfile -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest src/frontend/
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Build and push backend Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build --no-cache -f Dockerfile -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest .
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME_FRONTEND }}
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
          resource-group: ${{ env.RESOURCE_GROUP }}
          username: ${{ secrets.AZURE_APP_USERNAME }}
          password: ${{ secrets.AZURE_APP_PASSWORD }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME_BACKEND }}
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
          resource-group: ${{ env.RESOURCE_GROUP }}
          username: ${{ secrets.AZURE_APP_USERNAME }}
          password: ${{ secrets.AZURE_APP_PASSWORD }}