name: Build and deploy JAR app to Azure Web App - bzzeats

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build frontend
        run: |
          cd src/frontend
          npm install
          CI=false npm run build --no-warnings
          cd ../..

      - name: Build backend with Maven
        run: mvn clean package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: 'target/*.jar'
      
      - name: Upload artifact for frontend
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: 'src/frontend/build'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-app
          path: 'frontend'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
          custom-id: 'frontend'
          custom-folder: 'frontend'
